### ISSUE TITLE
Invisible Wall In OS Telemarketing Office

### ISSUE THREAD

**Issue by Gnarynhar** [deseven/osse#1]
Was going to report it on the Discord, but it's telling me I can't send messages there- so I'm putting it here.

In the public version's latest update in the telemarketing office I can't just walk into the back area. There's an invisible wall starting at the pot plant blocking off the rest of the room, except for a small corridor along the wall. Walking to the end and crouching allows me to jump up onto the carrels, and then walk along the to and gather cans/bottles/etc and even jump down to access the rest of the room. but I have to jump back up onto the carrels to get back out.

**Comment by deseven** [comment]
This is a repo for Open Sewer Save Editor - a now defunct project that was used to edit save files in early builds of Obenseuer. If you have any problems with Obenseuer, please create an issue in its official issue tracker:
https://github.com/loiste-interactive/Obenseuer-Issues/issues

**Comment by Gnarynhar** [comment]
Sorry, wasn''t playing close enough attention.
