### ISSUE TITLE
Kolhola A15 Lockpicking bug.

### ISSUE THREAD

**Issue by Gnarynhar** [deseven/osse#2]
When trying to lockpick the door for A15 in the Kolhola building, the lockpicking interface disappears  after a short amount of time, often before the arrow gets to the target area. To keep the interface open to pick the door you have to click immediately and sacrifice a lockpick. The interface then stays open and works as normal.

**Comment by deseven** [comment]
This is a repo for Open Sewer Save Editor - a now defunct project that was used to edit save files in early builds of Obenseuer. If you have any problems with Obenseuer, please create an issue in its official issue tracker:
https://github.com/loiste-interactive/Obenseuer-Issues/issues
